name: CI

on:
  pull_request:
    branches:
      - architecture_mvi
    paths:
      - README.md

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        run: echo "CI is considered successful because the Readme file was changed"